### ISSUE TITLE
gratis rooms

### ISSUE THREAD

**Issue by ghost** [Varkalandar/imp_city#1]
Hello. I understand this is in a very early status, but I think even this early status would be more interesting if rooms had a cost (and creatures would ask for some money as well).
This would require an early way to get money or resources to build rooms, so would likely require the forge to be accessible without research, or perhaps simply to allow the use of raw materials as payment means.

**Comment by Varkalandar** [comment]
In general I agree. There is a little problem though, that the player needs a forge to forge coins, and so the rooms up to the forge must be free to build. Maybe there are alternative solutions ... I'll spend some time thinking abou this.

The other point, creatures asking for money definitely will be added soon. Just recently I've added some code to let creatures gain experience and level up. So I can keep the level 1 creatures be free to start the dungeon, but higher level creatures will demand coins, and leave if not paid properly.

**Comment by ghost** [comment]
> There is a little problem though, that the player needs a forge to forge coins, and so the rooms up to the forge must be free to build. Maybe there are alternative solutions ... 

This is right. Or you can simply give a starting dungeon with a small treasure room and forge, players will probably get rid of them to rearrange the dungeon anyway, notably if the forge does not have resources near it.

**Comment by Varkalandar** [comment]
Starting with v0.27 furnishing the advanced rooms cost some copper coins per square. Rooms required to start a dungeon (farms, libraries, forges) remain free. Additional imps cost copper though.

**Comment by ghost** [comment]
That's great! I'll give a new round of testing to all that soon (and we'll see if your hopes about fixing stuff are just hopes or facts ;))
