### ISSUE TITLE
escape key quits the game

### ISSUE THREAD

**Issue by ghost** [Varkalandar/imp_city#3]
I would expect the escape key to only close the current window, instead, and game after a confirmation window if there is none.

**Comment by Varkalandar** [comment]
I agree. This is a remnant from the very early development stages. I'll change it to close the current window, and if there is no window open, bring up a dialog to load/save/exit the game and change settings..

**Comment by Varkalandar** [comment]
In v0.25 ESC closes the current dialog in the game.

**Comment by Varkalandar** [comment]
Implemented in v0.25
