### ISSUE TITLE
right click seems to drop artefacts

### ISSUE THREAD

**Issue by ghost** [Varkalandar/imp_city#4]
Well, I guess this is a debug feature not removed. Also, after imps caught those and put them in treasure room, nothing happened.

**Comment by Varkalandar** [comment]
Yes that's right, it's a leftover from debugging. I need to introduce a sort of master switch to turn this and similar code off in releases.

**Comment by ghost** [comment]
What is done in unvanquished (at least) is that there is a "cvar" (configuration variable) named "g_cheat" which is set to "true" when maps are loaded in "devmap" command instead of "map" command. This in turn allows to run a bunch of commands reserved to "cheat" (or debugging, ofc).

I think an early implementation would be to be able to take, say, --cheat as a runtime command-line parameter. It's always useful to have the debug features built-in, this way you have more reliable debug builds, since the inner code is the same between debug and release builds (that's at least valid for C and C++ which can enable code paths depending on that, I don't know for java).
Of course, it's just a suggestion, I doubt I'll be able to contribute anything to a java codebase, I'd need to re-learn the tooling and adapt me and my environment :)

**Comment by Varkalandar** [comment]
No longer available in v0.27
