### ISSUE TITLE
pathfinding problem

### ISSUE THREAD

**Issue by ghost** [Varkalandar/imp_city#7]
I uploaded a savegame where this bug happens. This is apparently not related to the lab tiles, I tried removing them and it didn't changed anything.
Also, I tried to dig in the walls to create an obvious path, and they would refuse to pave the missing tiles still.

![pathfindingbug-impcity](https://github.com/Varkalandar/imp_city/assets/1316300/6b93c11e-e513-4171-87c7-23c375cac1c2)
[savegame.zip](https://github.com/Varkalandar/imp_city/files/13325990/savegame.zip)

**Comment by Varkalandar** [comment]
I see. Thank you for providing the saved game, this is very helpful. I hope some day I will have fixed all the pathfinding issues.

**Comment by Varkalandar** [comment]
After some examination I can say, this is not a pathfinding problem. Actually, none of the imps feels bothered to do something about the floor there. The raw floor seems to be a side effect of a different problem, a axcavation job that didn't work as expected and left the floor undone.

I'll see what I can do about it.

**Comment by Varkalandar** [comment]
Should be fixed in v0.26, at least for the cases present in the savegame.
